### ISSUE TITLE
vault_approle_auth_backend_role crashing terraform ( v0.11.7 / v1.1.0 ) 

### ISSUE THREAD

**Issue by cqwense** [terraform-providers/terraform-provider-vault#118]
Hi there,

My issue is centered around the vault_approle_auth_backend_role resource , so I am opening an issue here before the terraform issue tracker.

I'm not go literate, but the panic line seems to indicate a conflict in datatype:

panic: interface conversion: interface {} is []interface {}, not string

The rest of requested info below:

### Terraform Version
> terraform --version
Terraform v0.11.7
+ provider.aws v1.18.0
+ provider.vault v1.1.0

### Affected Resource(s)
vault_approle_auth_backend_role

The 3 instances of the failing resource are named:

module.dkohl_safe.vault_approle_auth_backend_role.dev
module.dkohl_safe.vault_approle_auth_backend_role.qa
module.dkohl_safe.vault_approle_auth_backend_role.prod

In the debug/crash output gists below.

### Terraform Configuration Files ( admittedly truncated to the important bits  ) 
```
 resource "vault_approle_auth_backend_role" "dev" {
   backend   = "approle/" # this exists and works via the vault UI 
   role_name = "${var.project_name}-dev"
   policies  = ["${var.project_name}-dev-policy"]
}

# code is repeated foreach "qa" & "prod" 
```

### Debug Output
https://gist.github.com/cqwense/793e7cb78030eef0d97cb8c9c3444a90

### Panic Output
https://gist.github.com/cqwense/793e7cb78030eef0d97cb8c9c3444a90

### Expected Behavior
Approles would have gotten created in vault.

### Actual Behavior
Terraform Crash

### Important Factoids
As you can see from the output/crash.log I am using a module interface at the moment as it is my end-goal.  Given the specific resource failure vs the rest of the vault ( and other provider ) resources creating correctly AND the panic suggesting a datatype issue - I believe nothing about the module setup should be causing its own issue.

I'm also using a wrapper called terratool, its primary use is aws iam temporary keys management and beyond that passes all arguments to terraform.  Again I don't think this should be in scope, but don't want to leave anything out.

### References
None I am aware of.

**Comment by Briansbum** [comment]
This has been fixed in #103 and it's waiting for release.
