### ISSUE TITLE
unexpected EOF when setting up vault_approle_auth_backend_role

### ISSUE THREAD

**Issue by lancehudson** [terraform-providers/terraform-provider-vault#119]
### Terraform Version

```bash
$ terraform -v
Terraform v0.11.7

$ terraform init
* provider.vault: version = "~> 1.1"

```

### Affected Resource(s)
- vault_approle_auth_backend_role

### Terraform Configuration Files
```hcl
provider "vault" {
}

resource "vault_auth_backend" "approle" {
  type = "approle"
}

resource "vault_approle_auth_backend_role" "chat" {
  role_name = "chat"
  policies  = ["chat"]

  depends_on = ["vault_auth_backend.approle"]
}

```

### Debug Output
https://gist.github.com/lancehudson/5aa5abc4f15d6f6563c86f8984c45d9b

### Panic Output
https://gist.github.com/lancehudson/adb6ee905cb36ed17e8235c72b8e28fb

```
panic: interface conversion: interface {} is []interface {}, not string
```

### Expected Behavior
AppRole created and terraform pass

### Actual Behavior
AppRole created and terraform failed

### Steps to Reproduce
1. `terraform apply`

**Comment by Briansbum** [comment]
This was fixed in #103 and is waiting to be released.

**Comment by daanemanz** [comment]
Is there an ETA on a release? Asking for a friend.

**Comment by sidewinder12s** [comment]
Also asking for a friend.

**Comment by sidewinder12s** [comment]
@paddycarver Any ETA on this getting released? We just upgraded Vault and forgot to check if this got released.
