### ISSUE TITLE
Feature Request: PKI Secret Backend Support

### ISSUE THREAD

**Issue by jgiles** [terraform-providers/terraform-provider-vault#121]
We're users of the PKI secret backend, and it's quite painful to configure via Terraform if you're wiring together a bunch of `vault_generic_secret`s and `null_resource` hacks. In particular, you can't reasonably do the multi-step process for using intermediate CAs.

A few other issues (#71, #111) seem to have been motivated by the challenges here, but we're interested in adding first-class support. I may try to put together a PR for this; I've been intending to contribute it for a while.

**Comment by bhuisgen** [comment]
@jgiles check this PR #158. Thanks.

**Comment by tyrannosaurus-becks** [comment]
This exists now, one of the docs is [here](https://www.terraform.io/docs/providers/vault/r/pki_secret_backend.html) for getting started. Thanks!
