### ISSUE TITLE
vault_aws_auth_backend_role.resolve_aws_unique_ids setting not detected

### ISSUE THREAD

**Issue by daveadams** [terraform-providers/terraform-provider-vault#128]
### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

- vault_aws_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "backend" {
  type = "aws"
  path = "test-iam-auth"
}

resource "vault_aws_auth_backend_role" "broken-role" {
  backend = "${vault_auth_backend.backend.path}"
  role = "broken-role"
  auth_type = "iam"
  resolve_aws_unique_ids = false
  bound_iam_principal_arn = "arn:aws:iam::123456789012:role/MyLambdaRole"
}

resource "vault_generic_secret" "working-role" {
  path = "auth/test-iam-auth/role/working-role"
  data_json = <<JSON
{
  "auth_type": "iam",
  "resolve_aws_unique_ids": false,
  "bound_iam_principal_arn": "arn:aws:iam::123456789012:role/MyLambdaRole",
}
JSON
}
```

### Expected Behavior

Both the "working-role" and "broken-role" resources should successfully create roles for the AWS auth backend "test-iam-auth" which does not have any AWS creds configured.

### Actual Behavior

Got this error when applying the "broken-role" resource:

```failed updating the unique ID of ARN "arn:aws:iam::123456789012:role/MyLambdaRole": &errors.errorString{s:"unable to fetch client for account ID 123456789012 -- default client is for account 000011112222"}```

The error indicates that the `resolve_aws_unique_ids` setting is not being sent to the API. The "working-role" generic write works, as does manual invocation.

### Notes

I think I know what the solution is. I'm filing this to refer back to in the PR.

**Comment by krish7919** [comment]
Is there an update on this?

**Comment by tyrannosaurus-becks** [comment]
Fixed via https://github.com/terraform-providers/terraform-provider-vault/pull/222
