### ISSUE TITLE
Feature request: Add vault entity support

### ISSUE THREAD

**Issue by OperationalDev** [terraform-providers/terraform-provider-vault#174]
# Use Case

It would be cool to mange identity entities in vault with Terraform.

Right now, we're doing it with a combination of the UI/cli, but Terraform would just be better.

## Example Cli
```
vault write identity/entity name="bob" policies="base" \
     metadata=department="the unhashibles" \
     metadata=title="overlord"

vault write identity/entity-alias name="bob" \
     canonical_id=be57e6db-bf5d-a246-e931-fda108fc2639    \
     mount_accessor=auth_ldap_b44f9dc1
```

## Example Code
```
resource "vault_entity" "bob" {
  name     = "bob"
  policy   = ["base"]
  metadata = <<EOF
    {
      "department": "the unhashibles",
      "title": "overlord"
    }
  EOF
}

resource "vault_alias" "bob" {
  name         = "bob"
  canonical_id = "${resourse.vault_entity.bob.id}"
  backend      = "ldap"
}
```

**Comment by cvbarros** [comment]
I think #220 is waiting review/update that would implement this

**Comment by OperationalDev** [comment]
#220 adds identity groups support. I've reused most of @simonswine contribution to add entity support. See pull request #247

**Comment by tyrannosaurus-becks** [comment]
I believe this is done! See [here](https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_identity_entity.go).
