### ISSUE TITLE
vault_ldap_auth_backend_config issue

### ISSUE THREAD

**Issue by billyaustin84** [terraform-providers/terraform-provider-vault#187]
Hi,

Trying to use the `vault_ldap_auth_backend_config` resource and failing.

### Terraform Version
```
Terraform v0.11.8
+ provider.vault v1.1.4
```

### Affected Resource(s)
- vault_ldap_auth_backend_config

### Terraform Configuration Files
```hcl
resource "vault_ldap_auth_backend_config" "ldap" {
    backend      = "${vault_auth_backend.ldap.path}"
    url          = "ldap://dc1.example.com,ldap://dc2.example.com"
    userdn       = "cn=Users,dc=example,dc=com"
    userattr     = "sAMAccountName"
    groupdn      = "ou=Vault,ou=Security Groups,dc=example,dc=com"
    groupfilter  = "(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))"
    groupattr    = "cn"
    upndomain    = "example.com"
    insecure_tls = "true"
    starttls     = "false"
    binddn       = ""
    bindpass     = ""
    discoverdn   = "false"
}
```

### Expected Behavior
`terraform plan` creates execution plan

### Actual Behavior
The following error is returned:
`Error: vault_ldap_auth_backend_config.ldap: Provider doesn't support resource: vault_ldap_auth_backend_config`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by lawliet89** [comment]
The resource you are looking at is `vault_ldap_auth_backend`.

This is an issue in the documentation I am fixing in https://github.com/terraform-providers/terraform-provider-vault/pull/183

**Comment by billyaustin84** [comment]
@lawliet89 Many thanks, I've looked through your PR and all is working now.
