### ISSUE TITLE
"vault_auth_backend" should support backend configuration options

### ISSUE THREAD

**Issue by StyleT** [terraform-providers/terraform-provider-vault#203]
Hi,

Auth backends in Vault support configuration options like `max_lease_ttl` or `listing_visibility`. Right no there is no way to set them via TF. 

### Provider Version
1.1.4

### References
https://www.vaultproject.io/api/system/auth.html#parameters

**Comment by dhild** [comment]
👍 - would be nice to expose the `local` option as well.
