### ISSUE TITLE
vault_auth_backend should output an attribute to allow modules to depend on it

### ISSUE THREAD

**Issue by atheiman** [terraform-providers/terraform-provider-vault#218]
### Terraform Version

v0.11.8

### Affected Resource(s)

- vault_auth_backend

### Terraform Configuration Files

```hcl
# Mount approle auth backend
resource "vault_auth_backend" "approle" {
  type = "approle"
}

# Create policies and approle role for app 'my-app'
module "app_my-app" {
  source   = "app"
  app_name = "my-app"
  # Unfortunately vault_auth_backend doesnt output any attrs so there is no way to make this module
  # depend on the approle mount being created first. Because of this, terraform might have to be
  # applied twice the first time.
  depends_on = ["vault_auth_backend.approle.some_output_attr"]
}
```

I'm not aware of any other workaround to make a module depend on a resource if the resource doesn't output any attributes. This wouldn't be a problem if either 1) a module could use `depends_on` or 2) a resource in a module could depend on a resource outside of the module

**Comment by atheiman** [comment]
Actually I just found there is an `accessor` attribute on the `vault_auth_backend` resource that is [undocumented](https://www.terraform.io/docs/providers/vault/r/auth_backend.html) but is in the code., so I can depend on that for now.

**Comment by Phylu** [comment]
You should be able to just use `depends_on = ["vault_auth_backend.approle"]`. This is how it is documented to use the `depends_on` statement (https://www.terraform.io/intro/getting-started/dependencies.html#implicit-and-explicit-dependencies).

**Comment by atheiman** [comment]
Hmm I didn’t know you could list a resource type and name as a dependency, i thought it had to be an attribute
