### ISSUE TITLE
Transitioning to Go Modules

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [terraform-providers/terraform-provider-vault#223]
https://github.com/terraform-providers/terraform-provider-vault/pull/206 brings rise to a discussion regarding Go Modules. A useful background is located [here](https://research.swtch.com/vgo).

I am decidedly in favor of transitioning to Go Modules. However, they are a new and experimental feature, and there are some known issues such as [this](https://github.com/golang/go/issues/26794).

The purpose of this ticket is to gain community input on if, when, and how this repo should be transitioned to Go Modules.

**Comment by cvbarros** [comment]
IMO all providers should follow on Terraform Core for these large scale changes. 
Ofc they are able to evolve independently and faster than Terraform Core (and I think that's the general direction Hashicorp is aiming with Core changes), but I'd say to stick with Go version and same tooling that Core uses.

**Comment by bflad** [comment]
Its currently planned to transition the AWS provider to Go modules as part of the new RPC framework and HCL dependency updates with the Terraform 0.12 upgrade 🔜 .

If transitioning, I would encourage continuing to vendor dependencies via `go mod vendor` after the transition until stable Go module caches are deployed.

**Comment by tyrannosaurus-becks** [comment]
Closing, as this was completed.
