### ISSUE TITLE
Version 1.3.0 has a breaking change in vault_generic_secret

### ISSUE THREAD

**Issue by lattwood** [terraform-providers/terraform-provider-vault#229]
The preflight checks for `vault_generic_secret` accesses `/v1/sys/internal/ui/mounts/$PATH`, and it checks for a `404` StatusCode to determine whether fallback behaviour should be used.

Unfortunately, this path returns a `403` StatusCode on Vault 0.8.3, and not a `404` as expected.

### References

- GH-156
- GH-140

**Comment by tyrannosaurus-becks** [comment]
@lattwood can you link to where the 403 check is needed or submit a PR? If so I can get a v1.3.1 binary out on the sooner side.

**Comment by lattwood** [comment]
@tyrannosaurus-becks https://github.com/terraform-providers/terraform-provider-vault/pull/156/files#r231241814 is the only spot as far as I can tell.

**Comment by lattwood** [comment]
@tyrannosaurus-becks line in master: https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/kv_helpers.go#L94-L98

**Comment by DonBower** [comment]
we have discovered the same issue, with vault 0.9.5

**Comment by tyrannosaurus-becks** [comment]
@lattwood thanks!

**Comment by lattwood** [comment]
Thanks @tyrannosaurus-becks !

**Comment by lucymhdavies** [comment]
Thanks all. Had this same issue with Vault 0.9.6, and fix is confirmed to work for us 👍
