### ISSUE TITLE
Encrypt the Terraform state file

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [terraform-providers/terraform-provider-vault#249]
At AWS re:Invent, a user of the Terraform Vault Provider requested that we write a provider that would be solely for using Vault to encrypt the state file that Terraform outputs. He was unconcerned with likewise encrypting the configuration file and said it could be handled on his end. We didn't discuss feasibility or the technical approach. Logging this request here because I think it would be great and bears further consideration.

**Comment by krish7919** [comment]
I do not understand how would one decrypt the state file and where would the key be located?
This would be a chicken an egg problem where we would need the decrypted state file to get the vault endpoint and credentials to connect to it, but then we need to talk with Vault to decrypt the file in the first place?

**Comment by krish7919** [comment]
Projects like [terrahelp](https://github.com/opencredo/terrahelp) can encrypt fields in the `tfstate` or [git-crypt](https://github.com/AGWA/git-crypt) can help in encrypting specific files in a git repo, if it helps.

**Comment by rossigee** [comment]
@krish7919 - I expect the vault key would be specified in the `~/.vault-token` file or `VAULT_TOKEN` envvar, as per the Vault client lib. The backend would simply need to use the client lib to store/retrieve the contents of the tfstate file into a given key in a 'kv' key/value store.

**Comment by krish7919** [comment]
Well, this implies that the decrypting of the tfstate would be dependent on an external system/s. And going by `~/.vault-token`, I assume you mean Hashicorp Vault, which stores its token there. I had thought about this but the thing is, our HA Vault setup is managed by Terraform (!) and now, we would be back to the chicken and egg problem.

I would rather we use an external system, or add a flag/config in Terraform to prompt for password to do this.

**Comment by tyrannosaurus-becks** [comment]
I'm going to go ahead and close this issue. Thanks, everyone, for your comments. I now realize that this would need to occur in Terraform's core code, and a provider is simply not capable of this.
