### ISSUE TITLE
Feature Request > vault_gcp_secret_backend_role

### ISSUE THREAD

**Issue by kuwas** [terraform-providers/terraform-provider-vault#253]
# Feature Request

- Support `vault_gcp_secret_backend_role` similar to `vault_aws_secret_backend_role`
- Right now we're using the `vault_generic_secret` and manually writing to `gcp/roleset/(roleset-id)`, this resource does not track state properly and the path is being written to every time terraform is run
- This also creates weird glitches where if the terraform terminates mid-apply, the Vault GCP secret engine doesnt revoke the old service account and you end up with two in GCP for the same roleset.

### Terraform Version

`Terraform v0.11.10`

### Affected Resource(s)

- vault_gcp_secret_backend_role (do not exist yet)

**Comment by emilymye** [comment]
I'll take a look!

**Comment by kuwas** [comment]
@emilymye Thank you!

**Comment by tyrannosaurus-becks** [comment]
This has been added! https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_gcp_auth_backend_role.go

**Comment by kuwas** [comment]
@tyrannosaurus-becks Thanks!

**Comment by kuwas** [comment]
@tyrannosaurus-becks Is it possible to reopen this?

**Comment by tyrannosaurus-becks** [comment]
Ah gotcha! Yes.

**Comment by kuwas** [comment]
@tyrannosaurus-becks Thank you!

**Comment by emilymye** [comment]
Actually, looking more closely, it seems theres https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_gcp_secret_backend.go which doesn't show up in the Vault provider docs? Looks like @fatmcgav contributed it.

**Comment by kuwas** [comment]
@emilymye Yeah, I remember searching on Google and finding this once, then forgot about it.

**Comment by tyrannosaurus-becks** [comment]
This is now supported [here](https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_gcp_secret_roleset.go).
