### ISSUE TITLE
Error when generating PKI cert with TTL set to a string like 720h

### ISSUE THREAD

**Issue by jrasell** [terraform-providers/terraform-provider-vault#313]
When generating a PKI certificate the TTL is expected to be a `int`; whereas the [docs](https://www.vaultproject.io/api/secret/pki/index.html#generate-certificate) and CLI behaviour suggest this is incorrect and that TTLs can be passed like `720h`.

### Terraform Version
```
Terraform v0.11.11
+ provider.vault v1.5.0
```

### Affected Resource(s)
- `vault_pki_secret_backend_cert`

### Terraform Configuration Files
```hcl
resource "vault_pki_secret_backend_cert" "test_cert" {
  backend     = "${vault_mount.test_intermediate_ca.path}"
  name        = "${vault_pki_secret_backend_role.test.name}"
  common_name = "test"
  ttl         = "720h"
  format      = "pem_bundle"

  lifecycle {
    ignore_changes = ["*"]
  }
}
```

### Error output

```
Error: vault_pki_secret_backend_cert.test: ttl: cannot parse '' as int: strconv.ParseInt: parsing "720h": invalid syntax
```

**Comment by estein9825** [comment]
I assume this will allow empty string passes as well?
