### ISSUE TITLE
[vault_aws_auth_backend_role] Attribute resolve_aws_unique_ids is not set

### ISSUE THREAD

**Issue by DorianZaccaria** [terraform-providers/terraform-provider-vault#325]
Hi team,

### Terraform Version
Terraform v0.11.7
Vault v0.11.4
Terraform Vault Provider v1.5.0

### Affected Resource(s)
* vault_aws_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "aws" {
  type = "aws"
}

resource "vault_aws_auth_backend_role" "vault-role" {
  backend                        = "${vault_auth_backend.aws.path}"
  role                           = "vault-role"
  auth_type                      = "iam"
  bound_iam_principal_arns       = ["${var.vault_role_arn}"]
  max_ttl                        = 120
  policies                       = ["policy1", "policy2"]
  resolve_aws_unique_ids         = false
  ttl                            = 60
}
```

### Debug Output
Terraform plan output:
```hcl
  + vault_aws_auth_backend_role.vault-role
      id:                         <computed>
      allow_instance_migration:   <computed>
      auth_type:                  "iam"
      backend:                    "aws"
      bound_iam_principal_arns.#: "1"
      bound_iam_principal_arns.0: "arn:aws:iam::123456789012:role/TestRole"
      max_ttl:                    "120"
      policies.#:                 "2"
      policies.0:                 "policy1"
      policies.1:                 "policy2"
      resolve_aws_unique_ids:     "false"
      role:                       "vault-role"
      ttl:                        "60"
```

### Expected Behavior
The role should have been created with the attribute `resolve_aws_unique_ids` set to `false`.

### Actual Behavior
The role has been successfully created with the attribute `resolve_aws_unique_ids` set to `true`.

### Steps to Reproduce
Run terraform apply with the `vault_aws_auth_backend_role` resource defined as above. Assuming the AWS IAM role and policies exist, it should create a vault role with the attribute `resolve_aws_unique_ids` set to true instead of false.

### Important Factoids
It looks like this is a known issue, let me know if I should reopen one of the PRs/Issue listed below.

Also, once the vault role is created every time a terraform plan runs it will detect a diff between the file and the actual state as the attribute is not the same. 

### References
* https://github.com/terraform-providers/terraform-provider-vault/issues/128
* https://github.com/terraform-providers/terraform-provider-vault/pull/129
* https://github.com/terraform-providers/terraform-provider-vault/pull/222

**Comment by catsby** [comment]
Hello - I believe this was fixed in https://github.com/terraform-providers/terraform-provider-vault/pull/270. I'm going to close this for now, sorry for the late replay
