### ISSUE TITLE
private terraform enterprise with Provider Vault using Approle instead of Token

### ISSUE THREAD

**Issue by ehsanhub** [terraform-providers/terraform-provider-vault#351]
### Terraform Version
0.11.10

### Affected Resource(s)
Reading secrets 

### Terraform Configuration Files
provider "vault" "login_vault" {
  address = ""
  token = ""
}

### Expected Behavior
There is no built-in integration between Terraform Enterprise and Vault using any of Approle or other models the only way to login to Vault is using VAULT_TOKEN which has to get issued every time we want to run queue the job or apply it 

How can we use Approle id and Approle Secret id in our Terraform code so these gets saved as Env variables so everytime we want to run the code it doesn't need a temporary token ?
Something like 
provider "vault" "login_vault" {
  address = ""
  approle_id= ""
  secret_id=""
}

We saved our GCP JSON credentials in Vault and in PTFE we want to have a permanent credentials saved in env. variables so we can read the roleset and get the token from Vault for Provider Google .

Any idea or suggestion is highly appreciated 

Thanks

**Comment by Daegalus** [comment]
We have been having this same problem, and we really need Approle support in the provider, not just token.

**Comment by thomasbibb** [comment]
I've tested this to some degree recently and I can confirm AppRole does work with version 1.6 of the Vault Provider.  However upon further inspection of the Vault provider code there may be an issue if you are authenticating with a AppRole within a child namespace (not root).

**Comment by petems** [comment]
@thomasbibb How are you supplying the AppRole to the provider?

**Comment by lukemgriffith** [comment]
+1
