### ISSUE TITLE
vault_aws_auth_backend_role - policies ordering issue (triggers plan update)

### ISSUE THREAD

**Issue by Constantin07** [terraform-providers/terraform-provider-vault#385]
### Terraform Version
0.11.13
vault provider version 1.7.0

### Affected Resource(s)
- vault_aws_auth_backend_role

### Terraform Configuration Files
```hcl
# admin role
resource "vault_aws_auth_backend_role" "admin_access" {
  backend                  = "${vault_auth_backend.aws.path}"
  role                     = "admin-access"
  auth_type                = "iam"
  policies                 = ["default", "admin-access" ]
  bound_iam_principal_arns = ["arn:aws:iam::******:role/admin_role"]
}
```

### Expected Behavior
Subsequent re-runs of plan to not trigger changes.

### Actual Behavior
It triggers a change on every plan re-run even if applied many times.

```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ vault_aws_auth_backend_role.admin_access
      policies.0: "admin-access" => "default"
      policies.1: "default" => "admin-access"


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

### Steps to Reproduce
1. `terraform plan`

**Comment by aaronmell** [comment]
We are running into the same issue as well.

**Comment by lawliet89** [comment]
The fix is to change this [line](https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_aws_auth_backend_role.go#L227) to `schema.TypeSet`.

**Comment by lcgkm** [comment]
#224

**Comment by lawliet89** [comment]
@lcgkm #224 is not related to this. I think that issue should have been fixed by https://github.com/terraform-providers/terraform-provider-vault/pull/305
