### ISSUE TITLE
vault_namespace resource breaks without trailing slash upon reapply

### ISSUE THREAD

**Issue by drewmullen** [terraform-providers/terraform-provider-vault#390]
Hi there,

thanks for this feature, @petems ! i noticed one undesirable behavior

you can define the path without the trailing slash and the resource is built, however it fails upon re-applying

### Terraform Version
```
Terraform v0.11.13
+ provider.vault v1.7.0
```

### Affected Resource(s)
- vault_namespace

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "vault_namespace" "namespace" {
    path = "test"
}
```

### Expected Behavior
resource should either enforce paths ending with a trailing slash or should not flag as `change required` when reapplying 

### Actual Behavior
```
Terraform will perform the following actions:

  ~ vault_namespace.namespace
      path: "test/" => "test"
```

```
* vault_namespace.namespace: error writing to Vault: Error making API request.

URL: PUT http://<address>:8200/v1/sys/namespaces/test
Code: 400. Errors:

* namespace "test/" already exists
```

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/terraform-providers/terraform-provider-vault/pull/338

**Comment by petems** [comment]
Yep, this probably should've had func validation to not allow trailing `/`...

Opening a PR now

**Comment by drewmullen** [comment]
thanks, @petems . +1 for **not** enforcing the '/' in the `path` parameter

**Comment by petems** [comment]
Indeedy, in fact looking at the API itself, that's how its supposed to be:

```
	// Allowing writing to a path ending in / makes it extremely difficult to
	// understand user intent for the filesystem-like backends (kv,
	// cubbyhole) -- did they want a key named foo/ or did they want to write
	// to a directory foo/ with no (or forgotten) key, or...? It also affects
	// lookup, because paths ending in / are considered prefixes by some
	// backends. Basically, it's all just terrible, so don't allow it.
	if strings.HasSuffix(req.Path, "/") &&
		(req.Operation == logical.UpdateOperation ||
			req.Operation == logical.CreateOperation) {
		return logical.ErrorResponse("cannot write to a path ending in '/'"), nil
	}
```

https://github.com/hashicorp/vault/blob/8d15b09ed13423d206425ed070e3a72ebdba70b7/vault/request_handling.go#L430
