### ISSUE TITLE
0.12: "no available version is compatible with this version of Terraform"

### ISSUE THREAD

**Issue by zx8** [terraform-providers/terraform-provider-vault#424]
Since Terraform 0.12 was [officially released yesterday](https://www.hashicorp.com/blog/announcing-terraform-0-12), I tried to use it with this provider:

```

$ terraform init -upgrade

[...]

No available provider "vault" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.
```

Any chance we can get a 0.12-compatible version of `terraform-provider-vault` released?

**Comment by ttyS0** [comment]
This is a blocker for me as well, as I have the Vault provider integrated into all of my Terraform configs, so I can't start testing v0.12 until this is available.

**Comment by koalalorenzo** [comment]
Do we have an ETA for this? Would love to have my terraform setup working back again 😓

**Comment by LW81** [comment]
Really baffled to see that a provider for a Hashicorp product is stopping me from adopting Terraform 0.12 !
Please update....

**Comment by ronaldegmar** [comment]
I have the same problem:

0.12checklist
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Upgrade provider "vault" to a version that is compatible with Terraform 0.12.
  
  No compatible version is available for automatic installation at this time. If this provider is still supported (not archived) then a compatible release should be available soon. For more information, check for 0.12 compatibility tasks in the provider's issue tracker.

# Module `"ec2-wiki"`

Taking these steps before upgrading to Terraform v0.12 will simplify the upgrade process by avoiding syntax errors and other compatibility problems.

**Comment by luis-garza** [comment]
+1
Please update your own product providers!
This is blocking us to upgrade to latest version and get all the available goodies...

**Comment by paultyng** [comment]
This work is still ongoing, unfortunately the 0.12 work exposed some issues in the provider that also had to be addressed. You can see in the [working branch](https://github.com/terraform-providers/terraform-provider-vault/compare/0.12-sdk) exactly how many changes have been necessary to get this working the way it should for 0.12 and is also resulting in a major version bump.

The release should be out fairly soon though, my understanding is that the work seems almost complete, we are just finalizing some testing.

**Comment by jtcressy** [comment]
@paultyng Is this delaying the 1.9.0 release?

**Comment by paultyng** [comment]
See #446

**Comment by paultyng** [comment]
@jtcressy it shouldn't have, the work was in parallel, and 1.9 is out.

**Comment by ajchiarello** [comment]
@paultyng I just tested with Terraform v0.12.2 & vault-provider v1.9.0 - the plugin downloaded correctly with the init, but running terraform plan gave this error: Error: Failed to instantiate provider "vault" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by ttyS0** [comment]
@ajchiarello I think v0.12 support won't be available until PR #446 gets merged.

**Comment by paultyng** [comment]
@ttyS0 correct, there will be a v2.0.0 that supports 0.12 and it will properly download automatically in `terraform init` once published. The team just wanted to ship some other features prior to that release to get them out a little earlier.

**Comment by paultyng** [comment]
#446 is merged, this release should be going out shortly.
