### ISSUE TITLE
Cannot associate multiple policies with a role

### ISSUE THREAD

**Issue by dond00m** [terraform-providers/terraform-provider-vault#43]
### Terraform Version
Terraform v0.11.0
Terraform v0.10.4

### Affected Resource(s)
vault_aws_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_aws_auth_backend_role" "example" {
  role                                 = "test-role"
  auth_type                            = "iam"
  bound_iam_principal_arn              = "arn:aws:iam::11111111111:role/*"
  ttl                                  = 60
  max_ttl                              = 120
  policies                             = ["default", "admin"]
}
```
This config a shortened version of the resource example:  https://www.terraform.io/docs/providers/vault/r/aws_auth_backend_role.html

### Debug Output
https://gist.github.com/dond00m/2979149b76a6b0c794b83258fe8de814

### Expected Behavior
Create vault role that is associated with multiple policies 

### Actual Behavior
Terraform cannot convert the policy list and the vault role is not created.

Noting that terraform will not error out if the policy list is set to any of the following:

["default"]
[""]

However, it does not seem to actually make any changes to the policy association i.e when there are multiple policies, it will not remove those policies. 

### Steps to Reproduce
Specify more than one policy in policy list E.g
```
policies                             = ["default", "admin", "new"]
```
then apply
 `terraform apply`

**Comment by BSick7** [comment]
I believe this is happening only on older vaults.
The changelog for vault 0.8.3 has the following comments:
```
...policies can now be specified as a comma-delimited string or an array if using JSON as API input; on read, policies will be returned as an array...
```
https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#083-september-19th-2017

**Comment by dond00m** [comment]
@BSick7 Yes indeed, upgrading the server from **0.8.1** to **0.8.3** resolved this. I was able to run the above example config no problem. 

Closing this issue, thank you!
