### ISSUE TITLE
Vault Policies should be alphabetized by the provider

### ISSUE THREAD

**Issue by awwithro** [terraform-providers/terraform-provider-vault#436]
It looks like vault stores policies associated with a role in alphabetical order. That means if the resource doesn't order them, a plan will constantly show changes. It would be easy enough to sort the policies first but since this would need to be done by everything that uses policies, it makes sense to me that the provider should do this first before sending the data to vault.

```
  ~ module.my_role_module.vault_aws_auth_backend_role.my_role_auth
      policies.0:                                "a" => "b"
      policies.1:                                "b" => "a"
      policies.2:                                "c" => "d"
      policies.3:                                "d" => "c"
```

### Terraform Version
v0.11.13
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_auth_backend_role

I haven't tested this with other roles but I suspect the behavior is the same for any role that has policies attached to it

### Expected Behavior
After applying the plan, not changes should show up in the next plan

### Actual Behavior
Changes show up since vault changes the ordering of the policies

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a role with policies attached to it that aren't in alphabetical order
1. plan/apply to attach the policies
1. plan again and changes are present

**Comment by infa-bsurber** [comment]
As an aside, Vault also lowercases all policy names so the provider should do this as well as casing affects the ordering ('Z' sorts to be before 'a')

**Comment by infa-bsurber** [comment]
Though actually this is probably a duplicate of #286

**Comment by awwithro** [comment]
It does indeed sound like a dupe. I'll close this in favor of the linked issue
