### ISSUE TITLE
Document for vault_policy_document is missing from the website

### ISSUE THREAD

**Issue by hashitop** [terraform-providers/terraform-provider-vault#452]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform version: any
- vault provider >= 1.6

### Affected Resource(s)
Document for `vault_policy_document` data source

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Link to under `Data Sources` to `website/docs/d/policy_document.md` on [Vault provider website](https://www.terraform.io/docs/providers/vault/index.html)

### Actual Behavior
The link is not available

### Steps to Reproduce
- Navigate to [Vault provider website](https://www.terraform.io/docs/providers/vault/index.html)
- Check `Data Sources` section
- Policy Document data source is missing

### Important Factoids
N/A

### References
N/A

**Comment by bflad** [comment]
The sidebar has been updated via #453 and an out-of-band deployment of the website. 👍
