### ISSUE TITLE
Missing the Azure Secrets Engine

### ISSUE THREAD

**Issue by BrendanThompson** [terraform-providers/terraform-provider-vault#460]
On the latest version of both terraform and the vault provider it looks as though the functionality for Azure is extremely limited. There is a way to create the roles under the [Auth API](https://www.vaultproject.io/api/auth/azure/index.html) for Azure, however there is nothing under the [Secrets Engine](https://www.vaultproject.io/api/secret/azure/index.html) for Azure.

The latter is where the details of the SP are received, thus the TF provider when it comes to Azure is not up to scratch.

Is there currently any work / discussion underway around this feature set?

**Comment by marcpascual** [comment]
Similar to aws, having these would also be useful:
 
vault_azure_secret_backend
vault_azure_secret_backend_role

**Comment by petems** [comment]
Implemented `vault_azure_secret_backend ` https://github.com/terraform-providers/terraform-provider-vault/pull/481

**Comment by petems** [comment]
`vault_azure_secret_backend` is merged! Working on role now, need to figure out how to get the tests working...

**Comment by petems** [comment]
https://github.com/terraform-providers/terraform-provider-vault/pull/493 Merged! This can be closed when the next release goes out 👍
