### ISSUE TITLE
Error when creating/reading vault_jwt_auth_backend_role

### ISSUE THREAD

**Issue by MKaciuba** [terraform-providers/terraform-provider-vault#497]
### Terraform Version
Terraform v0.12.6
+ provider.aws v2.22.0
+ provider.vault v2.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_jwt_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_jwt_auth_backend" "gsuite" {
  type               = "oidc"
  path               = "oidc"
  oidc_discovery_url = "https://accounts.google.com"
  oidc_client_id     = var.client_id
  oidc_client_secret = var.client_secret
}

data "vault_policy_document" "admin" {
  rule {
    path         = "cubbyhole/*"
    capabilities = ["create", "read", "update", "delete", "list"]
  }
}

resource "vault_policy" "admin" {
  name   = "admin"
  policy = data.vault_policy_document.admin.hcl
}

resource "vault_jwt_auth_backend_role" "admin" {
  backend               = vault_jwt_auth_backend.gsuite.path
  role_type             = "oidc"
  role_name             = "admin"
  bound_audiences       = [var.client_id]
  user_claim            = "sub"
  oidc_scopes           = ["profile", "email", "openid"]
  allowed_redirect_uris = ["http://localhost:8250/oidc/callback", "${var.vault_addr}/ui/vault/auth/${vault_jwt_auth_backend.gsuite.path}/oidc/callback"]
  policies              = ["default", vault_policy.admin.id]
  ttl                   = 86400
  max_ttl               = 86400
  bound_claims          = {
    email = var.email
    hd    = var.hd
  }
  claim_mappings        = {
    email = "email"
  }
}
```

### Panic Output
https://gist.github.com/MKaciuba/8adb9dac1c533d5fd52ae9f9ea3419a8

### Expected Behavior
Resource vault_jwt_auth_backend_role.admin should be created with no crash.

### Actual Behavior
Resource vault_jwt_auth_backend_role.admin is created but terraform crashes.

### Steps to Reproduce
1. `terraform apply`

**Comment by anhdat** [comment]
I have the same issue when running against Vault 1.2.0/1.2.1, going back to use Vault 1.1.2 results no error.

**Comment by samvrocks** [comment]
Same problem here

`2019-08-09T12:28:07.833Z [DEBUG] plugin.terraform-provider-vault_v2.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:689 +0xa1
2019/08/09 12:28:07 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/08/09 12:28:07 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing`

**Comment by anhdat** [comment]
Compiled binary from `master` branch solved the issue with Vault 1.2.1. Only need to deprecate `ttl` to `token_ttl` and `policies` to `token_policicies`. Maybe it's time for a release.

**Comment by samvrocks** [comment]
With vault provider 2.2 version seems to work fine again. Thanks!

**Comment by MKaciuba** [comment]
I confirm, works as expected. Thank you.
