### ISSUE TITLE
0 TTL in `vault_mount` makes terraform continuously want to apply changes

### ISSUE THREAD

**Issue by wjam** [terraform-providers/terraform-provider-vault#5]
Setting `default_lease_ttl_seconds` or `max_lease_ttl_seconds` to 0 means that `terraform plan` will always want to apply changes. The reason for this is that zero gets translated as 'apply the default value' and so when reading for the next plan, Terraform will assume the TTL returned needs to be set back to zero.

Note that this will mean just resetting the mount back to the default TTL every time `plan` is run so shouldn't cause any real problems.

**Comment by radeksimko** [comment]
Closing as it was resolved via #6 

Thanks.
