### ISSUE TITLE
token_type parameter is missing on vault_gcp_auth_backend_role

### ISSUE THREAD

**Issue by komattaka** [terraform-providers/terraform-provider-vault#503]
## Terraform Version
```
Terraform v0.11.8
+ provider.vault v2.2.0
```

### Affected Resource(s)
- vault_gcp_auth_backend_role

### Terraform Configuration Files
```hcl
resource "vault_gcp_auth_backend_role" "gcp_service_account" {
  type                   = "iam"
  role                   = "test-service-account"
  backend                = "${vault_auth_backend.gcp_for_microservice.path}"
  bound_projects         = ["my-test-project"]
  bound_service_accounts = ["<GCP_SERVICE_ACCOUNT_EMAIL_ADDRESS>"]
  token_policies         = ["editor"]
  token_type             = "default"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
Terraform doesn't cause panic.

### Expected Behavior
`terraform apply` works correctly.

### Actual Behavior
The following error is occurred.
```
*vault_gcp_auth_backend_role.gcp_service_account: 1 error(s) occurred:

* vault_gcp_auth_backend_role.gcp_service_account: Error updating GCP auth role "auth/gcp/test-project/role/test-service-account": Error making API request.

URL: PUT https://<VAULT_URL>/v1/auth/gcp/test-project/role/test-service-account
Code: 422. Errors:

* 1 error occurred:
	* unknown fields: ["token_policies" "token_type"]
```

### Steps to Reproduce

1. `terraform apply` with the code above

`terraform plan` works correctly.

### Important Factoids
N/A

### References

This bug is similar to #393 

There's work-around as follows. Do not use `token_policies` and set `token_type` to "".

```
#  token_policies         = ["editor"]
#  token_type             = "default"

  policies   = ["editor"]
  token_type = ""
```

**Comment by lawliet89** [comment]
What version of Vault are you using?

**Comment by komattaka** [comment]
@lawliet89 
Thank you for your confirmation!
I'm using Vault 1.1.3... Sorry, close 🙇
