### ISSUE TITLE
Support kv_secret_backend

### ISSUE THREAD

**Issue by julianvmodesto** [terraform-providers/terraform-provider-vault#522]
Currently, we don't yet support the kv_secret_backend resource for the Vault KV Secrets Engine

https://www.vaultproject.io/docs/secrets/kv/index.html

**Comment by billyaustin84** [comment]
This is supported through the `vault_generic_secret` resource.

**Comment by peikk0** [comment]
Actually this is done using the [`vault_mount`](https://www.terraform.io/docs/providers/vault/r/mount.html) resource.

**Comment by julianvmodesto** [comment]
Oops, thanks!
