### ISSUE TITLE
Support for managing Vault audit backends

### ISSUE THREAD

**Issue by dantrauner** [terraform-providers/terraform-provider-vault#53]
It looks like this provider doesn't yet support enabling or configuring Vault's [audit backends](https://www.vaultproject.io/docs/audit/index.html) – does anyone using this provider to automate a Vault deployment via Terraform have a reasonable workaround for automating the enabling/configuration of one or more audit backends?

**Comment by alex1x** [comment]
I've used remote-exec in testing: start a Vault cluster, init it with remote-exec,  another remote-exec enables auditing, then apply terraform Vault configuration. Then you can run your tests. I suppose I would do the same for a production cluster with the exception of doing the init manually.
