### ISSUE TITLE
Improve aws secrets config using new config/read endpoint

### ISSUE THREAD

**Issue by kalafut** [terraform-providers/terraform-provider-vault#538]
As of https://github.com/hashicorp/vault/pull/7245, reading the root config is now possible. As a result we can probably improve: https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_aws_secret_backend.go#L164

**Comment by joelthompson** [comment]
I'll be happy to take a crack at this if nobody else has started.

**Comment by kalafut** [comment]
All yours!
