### ISSUE TITLE
database_secret_backend_connection templated credentials support

### ISSUE THREAD

**Issue by cparmar** [terraform-providers/terraform-provider-vault#542]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.8

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_database_secret_backend_connection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "vault_database_secret_backend_connection" "postgres" {
  backend       = "db"
  name          = var.database_name
  allowed_roles = "${var.database_name}-ro"

  postgresql {
    connection_url = "postgres://\{\{username\}\}:\{\{password\}\}@${var.address}:${var.port}/postgres"
    username = ${var.vault_user_username}
    password = ${var.vault_user_password}
  }
}
```

### Expected Behavior
Configure database secret backend with templated credentials to support database root credentials rotation as per https://learn.hashicorp.com/vault/secrets-management/db-root-rotation#step-2-configure-postgresql-secret-engine.

### Actual Behavior
Templated credentials are not supported. only static credentials are supported using the `connection_url` parameter.

**Comment by Wolfsrudel** [comment]
You'll have to use the `data` stanza.
`postgresql { # connection details} 
data {
  username = "" 
  password = "" 
}`
https://www.terraform.io/docs/providers/vault/r/database_secret_backend_connection.html#data

**Comment by cparmar** [comment]
This is exactly what I needed - thank you.
