### ISSUE TITLE
Token_type parameter is not supported in vault_jwt_auth_backend or in general any of the auth backend resources

### ISSUE THREAD

**Issue by shwuandwing** [terraform-providers/terraform-provider-vault#555]
The Vault Terraform provider is missing support for the token_type parameter in various vault_*_backend resources.   e.g.  see documentation.

https://www.vaultproject.io/api/system/auth.html#token_type

i.e.  Vault lets admins config the token type of each auth mount.

The Vault provider only supports config the token type for a role inside each auth mount.

### Terraform Version
Terraform version 0.12.9, Vault provider v2.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_jwt_auth_backend
- vault_auth_backend

### Expected Behavior
token_type in the /sys/auth/*/tune methods should be supported

### Actual Behavior
cannot set the token_type parameter in the /sys/auth/*/tune method with the vault_jwt_auth_backend or vault_jwt_auth_backend.

**Comment by kalafut** [comment]
@lawliet89 Were these deliberately omitted during https://github.com/terraform-providers/terraform-provider-vault/pull/478 (re: the JWT case)?

**Comment by lawliet89** [comment]
I only updated the roles for each auth backend. I didn't update the auth backends themselves.
