### ISSUE TITLE
'policy_arn' doesn't work for vault_aws_secret_backend_role 

### ISSUE THREAD

**Issue by jasonarewhy** [terraform-providers/terraform-provider-vault#60]
Hi - I posted this in the [google group](https://groups.google.com/forum/?pli=1#!topic/terraform-tool/ml7czM7B2jY) and was asked to submit an issue here by @paddycarver.

The issue:

I've defined a resource in a module that creates a Vault aws secret backend role for an IAM role that's created in the same module:

```
resource "aws_iam_role" "assumed_role" {
  name               = "${var.role_name}"
  path               = "/"
  assume_role_policy = "${data.aws_iam_policy_document.assumed_role_policy.json}"
}

resource "vault_aws_secret_backend_role" "role" {
  backend = "users/aws/master"
  name = "${var.role_name}"
  policy_arn = "${aws_iam_role.assumed_role.arn}"
}
```

Normally, outside of Terraform, in order to create the secret backend role in Vault, it'd look something like this:

```
> vault write users/aws/master/roles/<role_name> arn=arn:aws:iam::<aws_account>:role/<role_name>

Success! Data written to: users/aws/master/roles/<role_name>
```

So I was hoping I could do the same in Terraform.  However, when calling the module and applying, I'm seeing the following:

```
module.my_iam_role.vault_aws_secret_backend_role.role: Creating...
  backend:    "" => "users/aws/master"
  name:       "" => "<role_name>"
  policy_arn: "" => "arn:aws:iam::<aws_account>:role/<role_name>"
Releasing state lock. This may take a few moments...


Error: Error applying plan:


1 error(s) occurred:


* module.iam_role_name.vault_aws_secret_backend_role.role: 1 error(s) occurred:


* vault_aws_secret_backend_role.role: Error creating role "<role_name>" for backend "users/aws/master": Error making API request.


URL: PUT https://<vault_url>:8200/v1/users/aws/master/roles/<role_name>
Code: 500. Errors:


* 1 error occurred:


* Either policy or arn must be provided
```
At first I thought maybe STS roles just weren't supported, but after looking up [that error in the Vault code](https://github.com/hashicorp/vault/blob/81e18aeccdbb6ed712f567a3d24a76374a16032f/builtin/logical/aws/path_roles.go#L107), I noticed that it's expecting either 'arn' or 'policy' - there's no mention of 'policy_arn'. 

I then dug into [the Vault provider code](https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_aws_secret_backend_role.go#L70), and it just seems to be forwarding the payload to Vault API as 'policy_arn' rather than 'arn' as expected. I tested by simply changing `data["policy_arn"] = policyARN` to `data["arn"] = policyARN`, and the role was then configured as expected, no error.

Let me know if any further info would help! Thanks!

### Terraform Version
0.11.1

### Affected Resource(s)
- vault_aws_secret_backend_role

### Expected Behavior
Vault role should have been configured with an ARN by vault_aws_secret_backend_role resource.

### Actual Behavior
Error from vault provider that "policy" or "arn" needed to be configured.

### Steps to Reproduce
1. Create a vault_aws_secret_backend_role resource that defines 'policy_arn' instead of 'policy' and attempt to apply

**Comment by paddycarver** [comment]
Hi @jasonarewhy! Thanks for opening an issue. It looks like #49 has a fix for this, so hopefully we can get this fixed quickly.

**Comment by paddycarver** [comment]
#49 got merged, so this should be fixed in the next release!
