### ISSUE TITLE
vault_generic_secret exposing data during a destroy/add operation

### ISSUE THREAD

**Issue by bootswithdefer** [terraform-providers/terraform-provider-vault#693]
When a destroy/add (-/+) operation occurs on vault_generic_secret the data field is output in the plan, exposing secrets.

### Terraform Version
Terraform v0.12.21
Vault plugin 2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_generic_secret

### Terraform Configuration Files
```hcl
resource "vault_generic_secret" "db" {
  path = "secret/services/db/login"

  data_json = <<EOT
{
  "username":   "${var.master_username}",
  "password":   "${var.master_password}",
  "endpoint":   "${var.endpoint}"
}
EOT

}
```

### Debug Output
https://gist.github.com/bootswithdefer/664837f2433a28c49c18da463c2dddae

### Expected Behavior
Secret should be redacted with (sensitive value).

### Actual Behavior
Secret displayed in plan output.

### Steps to Reproduce
1. Create a generic vault secret with terraform
2. Change the vault path in the terraform to cause a destroy/create
3. terraform plan

**Comment by ingvarch** [comment]
Please use latest version(2.9.0) of vault plugin - your version is 2.0.0

```
Terraform will perform the following actions:

  # vault_generic_secret.db will be created
  + resource "vault_generic_secret" "db" {
      + data         = (sensitive value)
      + data_json    = (sensitive value)
      + disable_read = false
      + id           = (known after apply)
      + path         = "secret/services/db/login"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by bootswithdefer** [comment]
That works, thanks.
