### ISSUE TITLE
Backend LDAP user and groups not getting deleted when destroy is applied

### ISSUE THREAD

**Issue by leonardomn** [terraform-providers/terraform-provider-vault#812]
Hi there,

I'm facing an issue when creating a new User with `vault_ldap_auth_backend_user`. It works properly when planning and applying, including when destroying, but the user still in the Vault server. I tried to change providers with no luck. If deleting manually or using curl it works properly.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
Vault 1.3.0+prem
Terraform 0.12.24 (cli)
Terraform enterprise v202004-3

### Terraform Configuration Files
```hcl
provider "vault" {
  version = "2.11.0"
  address = var.vault_address

  auth_login {
    path = var.vault_auth_login_path

    parameters = {
      role_id   = var.role_id
      secret_id = var.secret_id
    }
  }
}

resource "vault_ldap_auth_backend_user" "main" {
  username = "username"
  policies = ["default"]
  backend  = ["ldap"]
}
```

### Expected Behavior
When applied it works properly, we have the user or group created and attached to the right backend and policy. When destroying, it should be removed from the users or groups list, it means, deleted.

### Actual Behavior
User or Group is created successfully `Apply complete! Resources: 2 added, 1 changed, 0 destroyed.` and attached to the right policy, but when destroying it return `Apply complete! Resources: 0 added, 0 changed, 2 destroyed.` but the user or groups still there.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform destroy`

### Important Factoids
No errors or issues are exposed to the users.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
No

**Comment by catsby** [comment]
Hello - 

I'm not able to reproduce this on Vault `1.3.0` with the provider version `2.11.0`. Are there any logs from Vault or Terraform you can safely share (removing sensitive info) for me to look at?

**Comment by catsby** [comment]
Following up here; I'm not able to reproduce this and I haven't heard back, so I'm going to close this for now.
