### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lwille** [terraform-providers/terraform-provider-vault#814]
We got a single incident of a panic while running a `terraform plan`. Stacktrace indicates a `runtime error` inside the Vault provider.

### Terraform Version
v0.12.26

Provider versions from log:
- hashicorp/vault `2.11.0`
- hashicorp/tfe `0.19.0`
- hashicorp/google `3.28.0`

### Affected Resource(s)
- `vault_generic_secret`, even though the crash seems to happen upon initialization of the provider

### Panic Output
As this error happened only once in our CI so far, we didn't manage to save the `crash.log`. 

However, here's a Stacktrace: https://gist.githubusercontent.com/lwille/34fb907216e4a87c4aabfa1f9481f378/raw/6b713b33df1a35ef0217ffdede23865f6c758cd8/stacktrace

### Expected Behavior
`terraform plan` should have succeeded

### Actual Behavior
`terraform plan` failed with `TERRAFORM CRASH`

### Steps to Reproduce
We didn't manage to reproduce this so far.

### Important Factoids
Running TF inside an `alpine:3.10` container

**Comment by catsby** [comment]
Hello - I looked into this a bit but I can't yet reproduce it. I'll leave this open in hopes someone else follows-up and can provide more information

**Comment by catsby** [comment]
Hello - I'm still unable to reproduce this, and we haven't heard back in some time. I'm going to close this for now. Please let us know if anyone has more information, and we can take another look.
