### ISSUE TITLE
vault_generic_endpoint always detecting configuration drift

### ISSUE THREAD

**Issue by papovyr** [terraform-providers/terraform-provider-vault#842]
Hi there,

Im trying to configure default_lease_ttl for vault as described [here](https://learn.hashicorp.com/tutorials/vault/tokens)
as many times i apply same TF script it will detect configuration drift

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Run dev instance `vault server -dev`
2. Export ENV vars 
```
VAULT_ADDR=http://localhost:8200
VAULT_TOKEN=YOUR_TOKEN
```
3. Create terraform file with following content 
### Terraform Configuration Files
```
resource "vault_generic_endpoint" "auth_token_default_lease_ttl" {
  path                 = "sys/mounts/auth/token/tune"
  disable_read         = false
  disable_delete       = true
  ignore_absent_fields = false

  data_json = <<EOT
{
  "default_lease_ttl": "12h",
  "max_lease_ttl": "12h"
}
EOT
}
```
4. Check vault endpoint before applying
```
vault read sys/mounts/auth/token/tune
```
(output)
```
Key                  Value
---                  -----
default_lease_ttl    768h
description          token based credentials
force_no_cache       false
max_lease_ttl        768h
token_type           default-service
```
5. apply terraform 
```
terraform init
terraform apply
```
6. check if endpoint modified 
```
vault read sys/mounts/auth/token/tune
```
(output)
```
Key                  Value
---                  -----
default_lease_ttl    12h
description          token based credentials
force_no_cache       false
max_lease_ttl        12h
token_type           default-service
```

7) Run `terraform apply` again. It will detect configuration drift 
As may time you try to do apply without any changes it will detect configuration drift and will update endpoint for each single apply

### Terraform Version
Terraform v0.12.29
provider.vault v2.12.2
Vault server version: tested on 1.4.0, 1.5.0, 1.4.2

**Comment by catsby** [comment]
The `data_json` field is receiving additional information from the Vault API. Checking the state file, it looks like this:

```
{
  "default_lease_ttl": 43200,
  "description": "token based credentials",
  "force_no_cache": false,
  "max_lease_ttl": 43200,
  "token_type": "default-service"
}
```

For configuring the auth token backend, we recommend you use the [`vault_auth_backend`  resource](https://www.terraform.io/docs/providers/vault/r/auth_backend.html) instead of `vault_generic_endpoint`

**Comment by kjvellajr** [comment]
@catsby can this issue be reopened? I am also using `vault_generic_endpoint` to configure a custom database plugin which shows configuration drift for every Terraform apply on the `data_json` field.

**Comment by Cajga** [comment]
One can ignore the field which are not defined in the data_json in the tf file with the [ignore_absent_fields = true](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/generic_endpoint#ignore_absent_fields) option.
