### ISSUE TITLE
The gcp_auth_backend is using deprecated vault api client method.

### ISSUE THREAD

**Issue by vsharma-ampion** [terraform-providers/terraform-provider-vault#858]
Hi there,

### Terraform Version
v0.13.0

### Affected Resource(s)
- vault_gcp_auth_backend

### Expected Behavior
The source code for this resource must use the vault api method 'EnableAuthWithOptions' for enabling the gcp authentication.

### Actual Behavior
The source code for this resource is using the deprecated method 'EnableAuth' for enabling the gcp authentication.

**Comment by kalafut** [comment]
Fixed in #861
