### ISSUE TITLE
Support TTL with vault_aws_access_credentials

### ISSUE THREAD

**Issue by nyurik** [terraform-providers/terraform-provider-vault#863]
The `data "vault_aws_access_credentials"` lets users get AWS credentials, but they all use default TTL. In some cases, this TTL is too short for the needed task, and needs to be increased.

### Affected Resource(s)
- `vault_aws_access_credentials`

### Terraform Configuration Files
```hcl
data "vault_aws_access_credentials" "route53" {
  backend = var.vault_aws_backend
  type    = "sts"
  role    = var.vault_aws_role
  ttl     = 3600   # <-- new property
}
```

**Comment by catsby** [comment]
I've opened #878 to add this
