### ISSUE TITLE
Vault auto_login example, can't auto_login using terraform 13 due to interpolation

### ISSUE THREAD

**Issue by runtman** [terraform-providers/terraform-provider-vault#912]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
13.5

### Affected Resource(s)
Vault provider - 2.16.0

### Terraform Configuration Files

```
provider "vault" {
  address = "var.vault_address"
  auth_login {
    path = format("auth/ldap/login/%s", var.username)
    parameters = {
      username = "var.username"
      password = "var.password"
    }
  }
}
```

### Debug Output

```
Error: Put "var.vault_address/v1/auth/ldap/login/anthony.cleaves": unsupported protocol scheme ""

```

### Expected Behavior
Authentication

### Actual Behavior
Error with interpolation

### Steps to Reproduce
Add above provider, then do `terraform plan`

### References
I turned the example here, into TF 13 syntax: https://registry.terraform.io/providers/hashicorp/vault/latest/docs#example-usage

--

Now i'm sure I am simply doing something wrong but I can't see to find much help from the internet on this one and the example is written for terraform 11.

In terraform 11 this would work:

```
provider "vault" {
    address      = "${var.vault_address}"
    auth_login {
        path       = "auth/ldap/login/${var.username}"
        parameters = {
            username = "${var.username}"
            password = "${var.password}"
        }      
    }
}
```

Now changing that into terraform 13 syntax, I do this and it does not work:

```
provider "vault" {
  address = "var.vault_address"
  auth_login {
    path = format("auth/ldap/login/%s", var.username)
    parameters = {
      username = "var.username"
      password = "var.password"
    }
  }
}
```

**Comment by catsby** [comment]
Hello @runtman  - can you try removing the quotes `"`? In Terraform 13 I believe that results in literal strings `var.vault_address` instead of interpolating. 

I believe this should work:

```hcl
provider "vault" {
  address = var.vault_address
  auth_login {
    path = format("auth/ldap/login/%s", var.username)
    parameters = {
      username = var.username
      password = var.password
    }
  }
}
```

I took a look at the link you shared and from what I saw, those do not contain quotes either. Let me know if that helps!

**Comment by runtman** [comment]
You're absolutely right, I have no idea how I didn't spot that. I am so sorry! 

Thank you.

**Comment by catsby** [comment]
@runtman no apologies needed, I'm glad you got things resolved 😄
