### ISSUE TITLE
LDAP Auth Backend Resource(s)

### ISSUE THREAD

**Issue by errygg** [terraform-providers/terraform-provider-vault#99]
Hi!

Would be great to have an auth backend resource for adding an LDAP connection similar to the Okta resources.

### Terraform Version
Terraform v0.11.7
Terraform Vault Provider v1.1.0

### Affected Resource(s)
New resource(s) for LDAP Auth Backend

### Terraform Configuration Files
```hcl
provider "vault" {
  version="~> 1.1"
}
```

### Debug Output
```
Error: module.test_vault_config.vault_ldap_auth_backend.ldap: Provider doesn't support resource: vault_ldap_auth_backend
```

### Expected Behavior
New resources would allow Vault to be configured to talk to an LDAP provider (such as Active Directory) and include the available options for LDAP auth.

### References
LDAP configuration is supported in Vault, just not yet available in this provider: https://www.vaultproject.io/docs/auth/ldap.html

**Comment by icereed** [comment]
Definitely need this +1

**Comment by lawliet89** [comment]
It's in [`v1.1.3`](https://github.com/terraform-providers/terraform-provider-vault/releases/tag/v1.1.3).

**Comment by sidewinder12s** [comment]
@tyrannosaurus-becks This can probably be closed out.
